import {
  SiGit,
  SiJavascript,
  SiNextdotjs,
  SiPostgresql,
  SiReact,
  SiTailwindcss,
  SiTypescript,
  SiHtml5,
  SiCss3,
  SiVite,
  SiRedux,
  SiJquery,
  SiNodedotjs,
  SiExpress,
  SiNestjs,
  SiMongodb,
  SiMongoose,
  SiMysql,
  SiAxios,
  SiPrisma,
  SiJest,
  SiCypress,
} from "react-icons/si";

export const skills = [
  { text: "React", Icon: SiReact },
  { text: "Next.js", Icon: SiNextdotjs },
  { text: "Tailwind", Icon: SiTailwindcss },
  { text: "PostgreSQL", Icon: SiPostgresql },
  { text: "Git", Icon: SiGit },
  { text: "Typescript", Icon: SiTypescript },
  { text: "Javascript", Icon: SiJavascript },
  { text: "HTML", Icon: SiHtml5 },
  { text: "CSS", Icon: SiCss3 },
  { text: "Redux", Icon: SiRedux },
  { text: "Node.js", Icon: SiNodedotjs },
  { text: "Express.js", Icon: SiExpress },
  { text: "Nest.js", Icon: SiNestjs },
  { text: "MongoDB", Icon: SiMongodb },
  { text: "Jest", Icon: SiJest },
  { text: "Cypress", Icon: SiCypress },
  { text: "Vite.js", Icon: SiVite },
  { text: "Axios", Icon: SiAxios },
  { text: "Prisma", Icon: SiPrisma },
  { text: "Mongoose", Icon: SiMongoose },
  { text: "MySQL", Icon: SiMysql },
  { text: "jQuery", Icon: SiJquery },
];
